apiVersion: apps/v1
kind: Deployment
metadata:
  name: travelhub-api
  labels:
    app: travelhub-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: travelhub-api
  template:
    metadata:
      labels:
        app: travelhub-api
    spec:
      containers:
      - name: api
        image: travelhub/api:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: travelhub-secrets
              key: redis-url
        - name: TRAVELPAYOUTS_TOKEN
          valueFrom:
            secretKeyRef:
              name: travelhub-secrets
              key: travelpayouts-token
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: travelhub-api-service
spec:
  selector:
    app: travelhub-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer
