apiVersion: apps/v1
kind: Deployment
metadata:
  name: travelhub-frontend
  namespace: travelhub
  labels:
    app: travelhub-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: travelhub-frontend
  template:
    metadata:
      labels:
        app: travelhub-frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/yourusername/travelhub-frontend:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: travelhub-frontend-service
  namespace: travelhub
spec:
  selector:
    app: travelhub-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
