version: '3.8'

services:
  # ========================================================================
  # IOS API Server
  # ========================================================================
  ios-api:
    build:
      context: .
      dockerfile: docker/Dockerfile.production
      args:
        - BUILD_DATE=${BUILD_DATE}
        - VERSION=${VERSION}
    image: ios-system:${VERSION:-latest}
    container_name: ios-api
    restart: unless-stopped
    
    environment:
      - IOS_ROOT_PATH=/data/ios-root
      - DATABASE_URL=postgresql+asyncpg://ios_user:${DB_PASSWORD}@postgres:5432/ios_db
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=false
    
    volumes:
      - ios-data:/data/ios-root
      - ios-uploads:/data/uploads
      - ios-exports:/data/exports
      - ./logs:/app/logs
    
    ports:
      - "8000:8000"
    
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    
    networks:
      - ios-network
    
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 2G
    
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # ========================================================================
  # PostgreSQL Database
  # ========================================================================
  postgres:
    image: postgres:15-alpine
    container_name: ios-postgres
    restart: unless-stopped
    
    environment:
      - POSTGRES_DB=ios_db
      - POSTGRES_USER=ios_user
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init.sql
    
    ports:
      - "5432:5432"
    
    networks:
      - ios-network
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ios_user -d ios_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    
    command:
      - "postgres"
      - "-c" 
      - "shared_buffers=256MB"
      - "-c"
      - "max_connections=100"
      - "-c"
      - "work_mem=16MB"

  # ========================================================================
  # Redis Cache
  # ========================================================================
  redis:
    image: redis:7-alpine
    container_name: ios-redis
    restart: unless-stopped
    
    command: >
      redis-server
      --appendonly yes
      --appendfsync everysec
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru
    
    volumes:
      - redis-data:/data
    
    ports:
      - "6379:6379"
    
    networks:
      - ios-network
    
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ========================================================================
  # Nginx Reverse Proxy
  # ========================================================================
  nginx:
    image: nginx:alpine
    container_name: ios-nginx
    restart: unless-stopped
    
    volumes:
      - ./nginx/nginx.production.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ios-exports:/usr/share/nginx/html/exports:ro
      - ./nginx/logs:/var/log/nginx
    
    ports:
      - "80:80"
      - "443:443"
    
    depends_on:
      - ios-api
    
    networks:
      - ios-network
    
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ========================================================================
  # Prometheus Monitoring
  # ========================================================================
  prometheus:
    image: prom/prometheus:latest
    container_name: ios-prometheus
    restart: unless-stopped
    
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./monitoring/alerts.yml:/etc/prometheus/alerts.yml:ro
      - prometheus-data:/prometheus
    
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=30d'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    
    ports:
      - "9090:9090"
    
    networks:
      - ios-network

  # ========================================================================
  # Grafana Dashboards
  # ========================================================================
  grafana:
    image: grafana/grafana:latest
    container_name: ios-grafana
    restart: unless-stopped
    
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_INSTALL_PLUGINS=redis-datasource
      - GF_SERVER_ROOT_URL=http://localhost:3000
    
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources:ro
    
    ports:
      - "3000:3000"
    
    networks:
      - ios-network
    
    depends_on:
      - prometheus

  # ========================================================================
  # Backup Service
  # ========================================================================
  backup:
    image: postgres:15-alpine
    container_name: ios-backup
    
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=ios_db
      - POSTGRES_USER=ios_user
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - BACKUP_SCHEDULE=0 2 * * *
    
    volumes:
      - ./backups:/backups
      - ./scripts/backup.sh:/backup.sh:ro
    
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        while true; do
          /backup.sh
          sleep 86400
        done
    
    networks:
      - ios-network
    
    depends_on:
      - postgres

# ============================================================================
# VOLUMES
# ============================================================================
volumes:
  ios-data:
    driver: local
  ios-uploads:
    driver: local
  ios-exports:
    driver: local
  postgres-data:
    driver: local
  redis-data:
    driver: local
  prometheus-data:
    driver: local
  grafana-data:
    driver: local

# ============================================================================
# NETWORKS
# ============================================================================
networks:
  ios-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16