version: '3.8'

services:
  # ========================================================================
  # Elasticsearch Cluster (3 nodes)
  # ========================================================================
  es01:
    image: elasticsearch:8.11.3
    container_name: ios-es01
    restart: unless-stopped
    
    environment:
      - node.name=es01
      - cluster.name=ios-es-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - xpack.security.enabled=true
      - xpack.security.enrollment.enabled=true
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    
    volumes:
      - es01-data:/usr/share/elasticsearch/data
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticsearch/config/synonyms.txt:/usr/share/elasticsearch/config/synonyms.txt:ro
    
    ports:
      - "9200:9200"
      - "9300:9300"
    
    networks:
      - ios-network
    
    healthcheck:
      test: ["CMD-SHELL", "curl -f -u elastic:${ELASTIC_PASSWORD} http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  es02:
    image: elasticsearch:8.11.3
    container_name: ios-es02
    restart: unless-stopped
    
    environment:
      - node.name=es02
      - cluster.name=ios-es-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    
    ulimits:
      memlock:
        soft: -1
        hard: -1
    
    volumes:
      - es02-data:/usr/share/elasticsearch/data
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    
    networks:
      - ios-network
    
    depends_on:
      - es01

  es03:
    image: elasticsearch:8.11.3
    container_name: ios-es03
    restart: unless-stopped
    
    environment:
      - node.name=es03
      - cluster.name=ios-es-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    
    ulimits:
      memlock:
        soft: -1
        hard: -1
    
    volumes:
      - es03-data:/usr/share/elasticsearch/data
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    
    networks:
      - ios-network
    
    depends_on:
      - es01

volumes:
  es01-data:
    driver: local
  es02-data:
    driver: local
  es03-data:
    driver: local

networks:
  ios-network:
    external: true