# monitoring/elk/filebeat/filebeat.yml

filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /logs/*.log
    json.keys_under_root: true
    json.add_error_key: true
    fields:
      service: ios-search
      environment: production

  - type: docker
    containers.ids: '*'
    processors:
      - add_docker_metadata: ~

output.logstash:
  hosts: ["logstash:5000"]

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644