# docker-compose.test.yml

version: '3.8'

services:
  postgres-test:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: test_ios_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "5433:5432"
    tmpfs:
      - /var/lib/postgresql/data

  elasticsearch-test:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ports:
      - "9201:9200"
    tmpfs:
      - /usr/share/elasticsearch/data

  qdrant-test:
    image: qdrant/qdrant:v1.7.0
    ports:
      - "6334:6333"
    tmpfs:
      - /qdrant/storage

  redis-test:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    tmpfs:
      - /data

  app-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    command: pytest tests/integration/ -v
    depends_on:
      - postgres-test
      - elasticsearch-test
      - qdrant-test
      - redis-test
    environment:
      - DATABASE_URL=postgresql://test_user:test_password@postgres-test:5432/test_ios_db
      - ELASTICSEARCH_URL=http://elasticsearch-test:9200
      - QDRANT_URL=http://qdrant-test:6333
      - REDIS_URL=redis://redis-test:6379/0
      - DJANGO_SETTINGS_MODULE=ios_core.settings.test
    volumes:
      - .:/app
      - test-results:/app/test-results

volumes:
  test-results: